version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  assignees:
  - alexander-lloyd
  ignore:
  - dependency-name: "@nrwl/angular"
    versions:
    - 11.2.0
    - 11.2.10
    - 11.2.11
    - 11.2.12
    - 11.2.7
    - 11.2.9
    - 11.3.0
    - 11.3.1
    - 11.3.2
    - 11.4.0
    - 11.5.1
    - 11.5.2
    - 11.6.0
    - 11.6.1
    - 12.0.0
    - 12.0.1
    - 12.0.4
    - 12.0.6
    - 12.0.7
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@nrwl/cli"
    versions:
    - 11.2.0
    - 11.2.10
    - 11.2.11
    - 11.2.12
    - 11.2.7
    - 11.2.9
    - 11.3.0
    - 11.3.1
    - 11.3.2
    - 11.4.0
    - 11.5.1
    - 11.5.2
    - 11.6.0
    - 11.6.1
    - 12.0.0
    - 12.0.1
    - 12.0.4
    - 12.0.6
    - 12.0.8
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@nrwl/linter"
    versions:
    - 11.2.0
    - 11.2.10
    - 11.2.11
    - 11.2.12
    - 11.2.7
    - 11.2.9
    - 11.3.0
    - 11.3.1
    - 11.3.2
    - 11.4.0
    - 11.5.1
    - 11.5.2
    - 11.6.0
    - 11.6.1
    - 12.0.0
    - 12.0.1
    - 12.0.4
    - 12.0.6
    - 12.0.8
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.2
    - 0.1101.3
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.10
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@nrwl/storybook"
    versions:
    - 11.2.0
    - 11.2.10
    - 11.2.11
    - 11.2.12
    - 11.2.7
    - 11.2.9
    - 11.3.0
    - 11.3.1
    - 11.3.2
    - 11.4.0
    - 11.5.1
    - 11.5.2
    - 11.6.0
    - 11.6.1
    - 12.0.0
    - 12.0.1
    - 12.0.4
    - 12.0.6
    - 12.0.8
  - dependency-name: "@nrwl/workspace"
    versions:
    - 11.2.0
    - 11.2.10
    - 11.2.11
    - 11.2.12
    - 11.2.7
    - 11.2.9
    - 11.3.0
    - 11.3.1
    - 11.3.2
    - 11.4.0
    - 11.5.1
    - 11.5.2
    - 11.6.0
    - 11.6.1
    - 12.0.0
    - 12.0.1
    - 12.0.4
    - 12.0.6
    - 12.0.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@nrwl/tao"
    versions:
    - 11.2.0
    - 11.2.10
    - 11.2.11
    - 11.2.12
    - 11.2.7
    - 11.2.9
    - 11.3.0
    - 11.3.1
    - 11.3.2
    - 11.4.0
    - 11.5.1
    - 11.5.2
    - 11.6.0
    - 11.6.1
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
    - 12.0.6
    - 12.0.8
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@nrwl/jest"
    versions:
    - 11.2.0
    - 11.2.10
    - 11.2.11
    - 11.2.12
    - 11.2.7
    - 11.2.9
    - 11.3.0
    - 11.3.1
    - 11.3.2
    - 11.4.0
    - 11.5.1
    - 11.5.2
    - 11.6.0
    - 11.6.1
    - 12.0.0
    - 12.0.1
    - 12.0.4
    - 12.0.6
    - 12.0.8
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@storybook/addon-a11y"
    versions:
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@nrwl/cypress"
    versions:
    - 11.2.0
    - 11.2.10
    - 11.2.11
    - 11.2.12
    - 11.2.7
    - 11.2.9
    - 11.3.0
    - 11.3.1
    - 11.3.2
    - 11.4.0
    - 11.5.1
    - 11.5.2
    - 11.6.0
    - 11.6.1
    - 12.0.0
    - 12.0.1
    - 12.0.4
    - 12.0.6
    - 12.0.8
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.5
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.0
    - 3.9.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/chrome"
    versions:
    - 0.0.133
    - 0.0.134
  - dependency-name: "@cypress/code-coverage"
    versions:
    - 3.9.3
    - 3.9.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: cypress
    versions:
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.4.0
    - 31.6.0
    - 31.6.1
    - 32.0.0
    - 32.0.1
    - 32.0.2
    - 32.1.0
    - 32.2.0
    - 32.3.0
    - 32.3.1
    - 32.3.2
  - dependency-name: "@angular-builders/custom-webpack"
    versions:
    - 11.0.0
    - 11.1.0
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: "@nrwl/eslint-plugin-nx"
    versions:
    - 11.2.0
    - 11.2.10
    - 11.2.11
    - 11.2.12
    - 11.2.7
    - 11.2.9
    - 11.3.0
    - 11.3.1
    - 11.3.2
  - dependency-name: ngx-date-fns
    versions:
    - 7.0.0
    - 7.0.2
  - dependency-name: "@babel/plugin-proposal-dynamic-import"
    versions:
    - 7.12.16
    - 7.12.17
  - dependency-name: ng-packagr
    versions:
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: "@angular-eslint/eslint-plugin-template"
    versions:
    - 1.1.0
